/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Classes.Asignature;
import Classes.Student;
import Model.SaveStudent;
import Model.UpdateStudentData;
import Model.UpdateStudentMB;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class UpdateStudent extends javax.swing.JFrame {
    UpdateStudentMB updateStudent;
    UpdateStudentData saveStudent;
    Student student;
    Asignature asignature;
    ArrayList<Asignature> ArrayList=new ArrayList<>(); 
    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
    }
    public void SetAsignature(){
        if(RadButtMatematicas.isSelected()){
            asignature= new Asignature("Matematicas","Ana Pérez Gómez","1234");
            ArrayList.add(asignature);
        }
        if(RadButtLenguaje.isSelected()){
            asignature= new Asignature("Lengua y literatura","José García Ruiz","1254");
            ArrayList.add(asignature);
        }
        if(RadButtFisica.isSelected()){
            asignature= new Asignature("Fisica","Juan Torres Castro","1278");
            ArrayList.add(asignature);
        }
        if(RadButtQuimica.isSelected()){
            asignature= new Asignature("Química","Marta Ortiz Salinas","1201");
            ArrayList.add(asignature);
        }
        if(RadButtBiologia.isSelected()){
            asignature= new Asignature("Biología","Sara Díaz López","1202");
            ArrayList.add(asignature);
        }
        if(RadButtHistoria.isSelected()){
            asignature= new Asignature("Historia","Patricia Ruiz Álvarez","1230");
            ArrayList.add(asignature);
        }
        if(RadButtGeografia.isSelected()){
            asignature= new Asignature("Geografía","Miguel Cabrera Gómez","1201");
            ArrayList.add(asignature);
        }
        if(RadButtEdFsica.isSelected()){
            asignature= new Asignature("Educación Física","Lucia Díaz Márquez","1270");
            ArrayList.add(asignature);
        }        
    }
    public void CleanTxt(){
        for (Component comp : jPanel1.getComponents()) {
            // Si el componente es un JTextField, limpia su texto
            if (comp instanceof JTextField) {
                ((JTextField) comp).setText("");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtFirstLastName = new javax.swing.JTextField();
        DateUpdate = new com.toedter.calendar.JDateChooser();
        TxtSearch = new javax.swing.JTextField();
        TxtSecondLastName = new javax.swing.JTextField();
        TxtIdentification = new javax.swing.JTextField();
        TxtPhone = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RadButtMatematicas = new javax.swing.JRadioButton();
        RadButtLenguaje = new javax.swing.JRadioButton();
        RadButtFisica = new javax.swing.JRadioButton();
        RadButtQuimica = new javax.swing.JRadioButton();
        RadButtBiologia = new javax.swing.JRadioButton();
        RadButtHistoria = new javax.swing.JRadioButton();
        RadButtGeografia = new javax.swing.JRadioButton();
        RadButtEdFsica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(TxtFirstLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 125, 158, -1));
        jPanel1.add(DateUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 57, 160, -1));

        TxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 61, 158, 22));
        jPanel1.add(TxtSecondLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 158, 158, -1));
        jPanel1.add(TxtIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 88, 158, -1));

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 120, 158, -1));
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 153, 158, -1));
        jPanel1.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 93, 158, -1));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 190, 89, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 78, 22));

        RadButtMatematicas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtMatematicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 233, -1, -1));

        RadButtLenguaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 253, -1, -1));

        RadButtFisica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 275, -1, -1));

        RadButtQuimica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 297, -1, -1));

        RadButtBiologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtBiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 233, -1, -1));

        RadButtHistoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 253, -1, -1));

        RadButtGeografia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtGeografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 275, -1, -1));

        RadButtEdFsica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadButtEdFsica, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 297, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema de Gestión de Notas (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void TxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchActionPerformed
        Object[] options = {"Buscar por nombre", "Buscar por Cedula", "Salir"};
        int option = JOptionPane.showOptionDialog(null, "Selecciona una opción:", "Opciones", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if(option==0){
            JOptionPane.showMessageDialog(null, "Buscar por Apellidos");
            
            updateStudent= new UpdateStudentMB(TxtName,TxtFirstLastName,TxtSecondLastName,DateUpdate,TxtIdentification,TxtPhone,TxtEmail);
            updateStudent.search("Ape_Paterno", TxtSearch.getText());
            
        }else if(option==1){
            JOptionPane.showMessageDialog(null, "Buscar por Cedula");
            updateStudent= new UpdateStudentMB(TxtName,TxtFirstLastName,TxtSecondLastName,DateUpdate,TxtIdentification,TxtPhone,TxtEmail);
            updateStudent.search("Cédula", TxtSearch.getText());
         
        }else{
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
            
        }
     
        
    }//GEN-LAST:event_TxtSearchActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        student= new Student(TxtName.getText(),TxtFirstLastName.getText(),
                TxtSecondLastName.getText(),DateUpdate.getDate(),
                TxtIdentification.getText(),TxtPhone.getText(),
                TxtEmail.getText(),ArrayList);
        saveStudent= new UpdateStudentData(student);
        saveStudent.setStudent();
        CleanTxt();
        JOptionPane.showMessageDialog(null, "Datos de "+student.getName()+" Actualizados con EXITO!");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateUpdate;
    private javax.swing.JRadioButton RadButtBiologia;
    private javax.swing.JRadioButton RadButtEdFsica;
    private javax.swing.JRadioButton RadButtFisica;
    private javax.swing.JRadioButton RadButtGeografia;
    private javax.swing.JRadioButton RadButtHistoria;
    private javax.swing.JRadioButton RadButtLenguaje;
    private javax.swing.JRadioButton RadButtMatematicas;
    private javax.swing.JRadioButton RadButtQuimica;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFirstLastName;
    private javax.swing.JTextField TxtIdentification;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPhone;
    private javax.swing.JTextField TxtSearch;
    private javax.swing.JTextField TxtSecondLastName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
